#!/usr/bin/env bash
set -uo pipefail

check_tracked_and_unmodified() {
    test_file=$1
    if ! git ls-files --error-unmatch $test_file 2> /dev/null ; then
        echo "File $test_file not tracked"
        exit
    fi
    if git ls-files -m | grep $test_file > /dev/null ; then
        echo "File $test_file modified since commit"
        exit
    fi
}

check_tracked_and_unmodified regressions

# Get list of regressions from test file
# Ignore commented tests
sed 's/#.*//' regressions | awk '/\yrun\y/ {print $2}' | while read test;
do
    check_tracked_and_unmodified tests/$test.c
    check_tracked_and_unmodified tests/expect_asm/$test.correct
    check_tracked_and_unmodified tests/expect_out/$test.correct
done

#git ls-files --error-unmatch tests/and

echo
echo "All good."